export const theme = {
  // Catppuccin Mocha accents over the user's native terminal background.
  background: "transparent",
  panel: "transparent",
  panelRaised: "transparent",
  overlay: "transparent",
  bar: "#313244",
  barSegment: "#45475a",
  onAccent: "#11111b",
  border: "#45475a",
  borderFocused: "#89b4fa",
  text: "#cdd6f4",
  muted: "#6c7086",
  subtle: "#9399b2",
  accent: "#89b4fa",
  accentStrong: "#cba6f7",
  selected: "transparent",
  success: "#a6e3a1",
  warning: "#f9e2af",
  danger: "#f38ba8",
  peach: "#fab387",
  teal: "#94e2d5",
  pink: "#f5c2e7",
  lavender: "#b4befe"
} as const;
